from foreing_services.hugging_face_service.leffa import HFLeffaTryOn
from foreing_services.hugging_face_service.catvton import HFCatVTONTryOn
from foreing_services.hugging_face_service.schemas import *
from foreing_services.hugging_face_service.nymbo import HFNymbo